[package]
name = "worker"
version.workspace = true
license.workspace = true
authors.workspace = true
publish.workspace = true
edition.workspace = true

[features]
default = []
accelerate = ["candle-core/accelerate", "candle-nn/accelerate"]
cuda = ["candle-core/cuda", "candle-nn/cuda"]
cudnn = ["candle-core/cudnn", "candle-nn/cudnn", "candle-nn/cuda"]
mkl = ["candle-core/mkl", "candle-nn/mkl"]
metal = ["candle-core/metal", "candle-nn/metal"]

[dependencies]
candle-core = { version = "0.11.0" }
candle-datasets = { version = "0.11.0" }
candle-nn = { version = "0.11.0" }
clap = { version = "4.5.4", features = ["derive"] }
prost = { version = "0.14.1" }
safetensors = { version = "0.8.0" }
thiserror = { version = "2.0.17" }
tokio = { version = "1.37.0", features = ["macros", "rt-multi-thread"] }
tonic = { version = "0.14.2" }
tonic-prost = { version = "0.14.2" }
tracing = { version = "0.1.40" }
tracing-subscriber = { version = "0.3.18" }

[build-dependencies]
tonic-prost-build = { version = "0.14.2" }

[dev-dependencies]
tokio = { version = "1.37.0", features = ["macros", "rt-multi-thread", "test-util"] }

[lints]
workspace = true
